name: portfolio
description: "Personal Flutter portfolio app showcasing my projects and experience."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4
  http: ^1.6.0
  intl: ^0.20.2
  timeline_tile: ^2.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/manrope/
    - assets/fonts/space_grotesk/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/manrope/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/manrope/Manrope-Light.ttf
          weight: 300
        - asset: assets/fonts/manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/Manrope-ExtraBold.ttf
          weight: 800
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Light.ttf
          weight: 300
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/space_grotesk/SpaceGrotesk-Bold.ttf
          weight: 700
